spring.application.name=modClientes
server.port=8081
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=bd_latinoamericano;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=p@ssw0rd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.rabbitmq.host=localhost
spring.rabbitmq.port=1433
<<<<<<< HEAD
spring.rabbitmq.username=user
spring.rabbitmq.password=12345
=======

spring.rabbitmq.username=user
spring.rabbitmq.password=12345

spring.security.user.name=admin
spring.security.user.password=123
>>>>>>> efdd037feaa801c86f3db3d1fef0d466530b8561
